seed: 42

# Article sampling - TINY TEST
max_articles_global: 20            # super tiny for testing
max_articles_per_country: 5        # cap to spread breadth
country_whitelist: []              # optional subset; empty = all
cluster_min_size: 2                # clusters smaller than this are skipped

# Pair sampling - TINY TEST
target_pairs_total: 5              # just 5 pairs for testing
cross_country_ratio: 0.40          # 60% within, 40% cross-country
pairs_per_cluster_min: 1
pairs_per_cluster_max: 3
max_pairs_per_article: 2           # target "degree" for BT solver
balance_by_outlet: true

# LLM judging
votes_per_pair: 1                  # just 1 vote for testing
truncate_chars_per_side: 500       # short for testing
pivot_language: "en"               # translate both sides to this for judging
use_translation: false             # disable for testing
entity_masking: false              # disable for testing

# Cost estimator
price_per_mtoken_usd: 0.15
tokens_per_call_estimate: 500      # very conservative for testing
dry_run: false                     # LIVE CALLS for testing

# Scoring/calibration
scoring_method: "anchors"          # "anchors" | "bt_offsets"
anchors_per_axis: 3                # fewer anchors for testing
country_isotonic_calibration: false  # disable for small test